In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [3]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [5]:
median_salary_year = df['salary_year_avg'].median()

In [6]:
median_salary_hour = df['salary_hour_avg'].median()

In [11]:
df_filled = df
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)

In [13]:
df_filled
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [15]:
df_filled['salary_hour_avg']

0         45.98
1         45.98
2         45.98
3         45.98
4         45.98
          ...
785736    45.98
785737    45.98
785738    45.98
785739    45.98
785740    45.98
Name: salary_hour_avg, Length: 785741, dtype: float64

In [21]:
df_filled.loc[:, 'salary_year_avg':'salary_hour_avg']

        salary_year_avg  salary_hour_avg
0              115000.0            45.98
1              115000.0            45.98
2              115000.0            45.98
3              115000.0            45.98
4              115000.0            45.98
...                 ...              ...
785736         115000.0            45.98
785737         115000.0            45.98
785738         115000.0            45.98
785739         115000.0            45.98
785740         115000.0            45.98

[785741 rows x 2 columns]

In [26]:
df_unique = df_filled
df_unique = df_unique.drop_duplicates()

print('Length of original df:       ', len(df_filled))
print('Length of drop duplicates df:', len(df_unique))
print('Rows Dropped:                ', len(df_filled)-len(df_unique))

Length of original df:        785741
Length of drop duplicates df: 785640
Rows Dropped:                 101

In [28]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

print('Length of original df:       ', len(df_filled))
print('Length of drop duplicates df:', len(df_unique))
print('Rows Dropped:                ', len(df_filled)-len(df_unique))

Length of original df:        785741
Length of drop duplicates df: 508042
Rows Dropped:                 277699