In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [ ]:
df.index.name = 'job_index'

In [ ]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [ ]:
df_usa = df[df['job_country'] == 'United States']

In [ ]:
Median_pivot = df_usa.pivot_table(values='salary_year_avg', index='job_title_short', aggfunc=('median', 'min', 'max'))

In [ ]:
Median_pivot

                                max    median      min
job_title_short
Business Analyst           387460.0   90000.0  35000.0
Cloud Engineer             221844.0  116100.0  42000.0
Data Analyst               375000.0   90000.0  25000.0
Data Engineer              525000.0  125000.0  23496.0
Data Scientist             960000.0  130000.0  30000.0
Machine Learning Engineer  315000.0  150000.0  44408.5
Senior Data Analyst        425000.0  110000.0  35360.0
Senior Data Engineer       375000.0  150000.0  45000.0
Senior Data Scientist      475000.0  155000.0  55000.0
Software Engineer          375000.0  130000.0  48982.0

In [ ]:
Median_pivot.sort_values(by='median', ascending=True)

                                max    median      min
job_title_short
Business Analyst           387460.0   90000.0  35000.0
Data Analyst               375000.0   90000.0  25000.0
Senior Data Analyst        425000.0  110000.0  35360.0
Cloud Engineer             221844.0  116100.0  42000.0
Data Engineer              525000.0  125000.0  23496.0
Data Scientist             960000.0  130000.0  30000.0
Software Engineer          375000.0  130000.0  48982.0
Machine Learning Engineer  315000.0  150000.0  44408.5
Senior Data Engineer       375000.0  150000.0  45000.0
Senior Data Scientist      475000.0  155000.0  55000.0